# Generated by Django 6.0.2 on 2026-02-22 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион/область')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('humidity', models.FloatField(verbose_name='Влажность (%)')),
                ('precipitation', models.FloatField(default=0, verbose_name='Осадки (мм)')),
                ('wind_speed', models.FloatField(default=0, verbose_name='Скорость ветра (м/с)')),
                ('pressure', models.FloatField(default=0, verbose_name='Давление (гПа)')),
                ('is_forecast', models.BooleanField(default=False, verbose_name='Это прогноз?')),
                ('source', models.CharField(default='api', max_length=50, verbose_name='Источник данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='climate.city')),
            ],
            options={
                'verbose_name': 'Данные погоды',
                'verbose_name_plural': 'Данные погоды',
                'db_table': 'weather_data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClimateNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Месяц (1-12)')),
                ('avg_temperature', models.FloatField(verbose_name='Средняя температура (°C)')),
                ('avg_humidity', models.FloatField(verbose_name='Средняя влажность (%)')),
                ('avg_precipitation', models.FloatField(verbose_name='Средние осадки (мм)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_norms', to='climate.city')),
            ],
            options={
                'verbose_name': 'Климатическая норма',
                'verbose_name_plural': 'Климатические нормы',
                'db_table': 'climate_norm',
                'unique_together': {('city', 'month')},
            },
        ),
    ]
