# Generated by Django 6.0.2 on 2026-02-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_ID', models.AutoField(primary_key=True, serialize=False)),
                ('loc_ID', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион/область')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('weather_data_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('humidity', models.FloatField(verbose_name='Влажность (%)')),
                ('precipitation', models.FloatField(default=0, verbose_name='Осадки (мм)')),
                ('wind_speed', models.FloatField(default=0, verbose_name='Скорость ветра (м/с)')),
                ('pressure', models.FloatField(default=0, verbose_name='Давление (гПа)')),
                ('is_forecast', models.BooleanField(default=False, verbose_name='Это прогноз?')),
                ('source', models.CharField(default='api', max_length=50, verbose_name='Источник данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='climate.city')),
            ],
            options={
                'db_table': 'weather_data',
            },
        ),
    ]
