# Generated by Django 6.0.2 on 2026-02-24 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('imageUri', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
            options={
                'db_table': 'crop',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locations_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('area', models.FloatField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('chernozem', 'Чернозем'), ('clay', 'Глина'), ('sandy', 'Песок'), ('loam', 'Суглинок'), ('peat', 'Торф'), ('podzolic', 'Подзолистая'), ('gray_forest', 'Серая лесная'), ('chestnut', 'Каштановая'), ('saline', 'Засоленная'), ('rocky', 'Каменистая')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('location_type', models.CharField(choices=[('open_ground', 'Открытый грунт'), ('greenhouse', 'Теплица'), ('pot', 'Горшок/контейнер'), ('raised_bed', 'Высокая грядка'), ('hydroponics', 'Гидропоника')], max_length=50)),
                ('imageUri', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('planting_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('planted_date', models.DateTimeField()),
                ('expected_harvest_date', models.DateTimeField()),
                ('area', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Активно'), ('harvested', 'Собрано'), ('failed', 'Погибло'), ('dormant', 'В состоянии покоя')], default='active', max_length=20)),
                ('imageUri', models.ImageField(blank=True, null=True, upload_to='plantings/')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.crop')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='farming.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planting',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('hist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farming.location')),
                ('planting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farming.planting')),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('disease_detection_ID', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(upload_to='diseases/')),
                ('detected_disease', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('recommended_action', models.TextField()),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='farming.planting')),
            ],
            options={
                'db_table': 'disease_detection',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendations_ID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('watering', 'Полив'), ('fertilizing', 'Удобрение'), ('harvest', 'Сбор урожая'), ('disease', 'Болезнь'), ('weather', 'Погода'), ('planting', 'Посадка'), ('care', 'Уход')], max_length=50)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=20)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('planting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farming.planting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('variety_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('imageUri', models.ImageField(blank=True, null=True, upload_to='varieties/')),
                ('optimal_temp_min', models.FloatField()),
                ('optimal_temp_max', models.FloatField()),
                ('optimal_humidity', models.FloatField()),
                ('soil_humidity', models.FloatField()),
                ('growth_days', models.IntegerField()),
                ('risk_factors', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('recommended_seedling_time', models.TextField(blank=True)),
                ('recommended_open_ground_time', models.TextField(blank=True)),
                ('recommended_greenhouse_time', models.TextField(blank=True)),
                ('seedling_age', models.TextField(blank=True)),
                ('soil_preparation', models.TextField(blank=True)),
                ('sowing_depth', models.TextField(blank=True)),
                ('planting_scheme', models.TextField(blank=True)),
                ('watering_after_planting', models.TextField(blank=True)),
                ('favorable_conditions', models.TextField(blank=True)),
                ('watering_recommendations', models.TextField(blank=True)),
                ('fertilizing_schedule', models.TextField(blank=True)),
                ('loosening_and_mulching', models.TextField(blank=True)),
                ('disease_prevention', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='farming.crop')),
            ],
            options={
                'db_table': 'variety',
            },
        ),
        migrations.AddField(
            model_name='planting',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farming.variety'),
        ),
        migrations.CreateModel(
            name='FavoriteCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранная культура',
                'verbose_name_plural': 'Избранные культуры',
                'db_table': 'favorite_crops',
                'unique_together': {('user', 'crop')},
            },
        ),
    ]
