# Generated by Django 6.0.2 on 2026-02-22 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Культура',
                'verbose_name_plural': 'Культуры',
                'db_table': 'crop',
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diseases/', verbose_name='Фото')),
                ('detected_disease', models.CharField(max_length=200, verbose_name='Обнаруженная болезнь')),
                ('confidence', models.FloatField(verbose_name='Уверенность (%)')),
                ('detection_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обнаружения')),
                ('recommended_action', models.TextField(verbose_name='Рекомендуемые действия')),
            ],
            options={
                'verbose_name': 'Обнаружение болезни',
                'verbose_name_plural': 'Обнаружения болезней',
                'db_table': 'disease_detection',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История действий',
                'db_table': 'history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название участка')),
                ('region', models.CharField(max_length=100, verbose_name='Регион/область')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Площадь (м²)')),
                ('soil_type', models.CharField(blank=True, choices=[('chernozem', 'Чернозем'), ('clay', 'Глина'), ('sandy', 'Песок'), ('loam', 'Суглинок'), ('peat', 'Торф'), ('podzolic', 'Подзолистая'), ('gray_forest', 'Серая лесная'), ('chestnut', 'Каштановая'), ('saline', 'Засоленная'), ('rocky', 'Каменистая')], max_length=50, verbose_name='Тип почвы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('location_type', models.CharField(choices=[('open_ground', 'Открытый грунт'), ('greenhouse', 'Теплица'), ('pot', 'Горшок/контейнер'), ('raised_bed', 'Высокая грядка'), ('hydroponics', 'Гидропоника')], max_length=50, verbose_name='Тип расположения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Фото')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название посадки')),
                ('planted_date', models.DateTimeField(verbose_name='Дата посадки')),
                ('expected_harvest_date', models.DateTimeField(verbose_name='Ожидаемая дата сбора')),
                ('area', models.FloatField(verbose_name='Площадь посадки (м²)')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('harvested', 'Собрано'), ('failed', 'Погибло'), ('dormant', 'В состоянии покоя')], default='active', max_length=20, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plantings/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Посадка',
                'verbose_name_plural': 'Посадки',
                'db_table': 'planting',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('watering', 'Полив'), ('fertilizing', 'Удобрение'), ('harvest', 'Сбор урожая'), ('disease', 'Болезнь'), ('weather', 'Погода'), ('planting', 'Посадка'), ('care', 'Уход')], max_length=50, verbose_name='Тип')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=20, verbose_name='Приоритет')),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'db_table': 'recommendations',
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сорта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='varieties/', verbose_name='Фото')),
                ('optimal_temp_min', models.FloatField(verbose_name='Мин. температура (°C)')),
                ('optimal_temp_max', models.FloatField(verbose_name='Макс. температура (°C)')),
                ('optimal_humidity', models.FloatField(verbose_name='Оптимальная влажность воздуха (%)')),
                ('soil_humidity', models.FloatField(verbose_name='Влажность почвы (%)')),
                ('growth_days', models.IntegerField(verbose_name='Дней до созревания')),
                ('risk_factors', models.TextField(blank=True, verbose_name='Факторы риска')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('recommended_seedling_time', models.TextField(blank=True, verbose_name='Сроки посева на рассаду')),
                ('recommended_open_ground_time', models.TextField(blank=True, verbose_name='Сроки высадки в открытый грунт')),
                ('recommended_greenhouse_time', models.TextField(blank=True, verbose_name='Сроки высадки в теплицу')),
                ('seedling_age', models.TextField(blank=True, verbose_name='Возраст рассады')),
                ('soil_preparation', models.TextField(blank=True, verbose_name='Подготовка почвы')),
                ('sowing_depth', models.TextField(blank=True, verbose_name='Глубина посева')),
                ('planting_scheme', models.TextField(blank=True, verbose_name='Схема посадки')),
                ('watering_after_planting', models.TextField(blank=True, verbose_name='Полив после посадки')),
                ('favorable_conditions', models.TextField(blank=True, verbose_name='Благоприятные условия')),
                ('watering_recommendations', models.TextField(blank=True, verbose_name='Рекомендации по поливу')),
                ('fertilizing_schedule', models.TextField(blank=True, verbose_name='График подкормок')),
                ('loosening_and_mulching', models.TextField(blank=True, verbose_name='Рыхление и мульчирование')),
                ('disease_prevention', models.TextField(blank=True, verbose_name='Профилактика болезней')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сорт',
                'verbose_name_plural': 'Сорта',
                'db_table': 'variety',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.crop')),
            ],
            options={
                'verbose_name': 'Избранная культура',
                'verbose_name_plural': 'Избранные культуры',
                'db_table': 'favorite_crops',
            },
        ),
    ]
