# Generated by Django 6.0.2 on 2026-02-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='risk_factors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
