# Generated by Django 6.0.2 on 2026-02-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
        ('farming', '0002_alter_variety_description_alter_variety_risk_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='climate.city'),
        ),
    ]
