# Generated by Django 6.0.2 on 2026-03-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('open_ground', 'поле'), ('greenhouse', 'теплица'), ('raised_bed', 'грядка'), ('other', 'другое')], max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('alluvial', 'Аллювиальные (речных долин) почвы'), ('podzolic', 'Дерново-подзолистые почвы'), ('forest', 'Лёсовые почвы'), ('sandy', 'Песчаные почвы'), ('podzol', 'Подзолистые почвы'), ('saline', 'Серозёмы'), ('gray_forest', 'Серые лесные почвы'), ('solonetz', 'Солонцы'), ('loam', 'Супесчаные и суглинистые почвы'), ('peat', 'Торфяные почвы (болотные)'), ('chernozem', 'Чернозём типичный'), ('chestnut', 'Чернозём южный (каштановый)')], max_length=50),
        ),
    ]
